version: "3"

services:
  gridsome:
    build:
      # context配下のDockefileを参照する
      context: "./gridsome"
      dockerfile: "Dockerfile"
    container_name: gridsome
    ports:
      # 左がホスト，右がコンテナ
      - 8080:8080
    # コンテナを立ち上げ続ける
    tty: true
    volumes:
      - ./app/my-blog:/app/my-blog
      - ./app/gridsome.sh:/app/gridsome.sh
    # 作業ディレクトリ
    working_dir: /app
    # 実行するコマンド
    command: sh -c "sh gridsome.sh"

  strapi:
    image: "strapi/strapi"
    container_name: strapi
    ports:
      - 8081:1337
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: mysql
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./app/my-blog-api:/usr/src/api/strapi-app
    depends_on:
      - mysql
    restart: always

  mysql:
    container_name: mysql
    image: "mysql:8.0.21"
    command: "--default-authentication-plugin=mysql_native_password"
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db:/var/lib/mysql

  nginx:
    image: "nginx:1.19.1-alpine"
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - gridsome
      - strapi
      - mysql
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  db:
